server:
  port: 8080
#  servlet:
#    context-path: /joey


spring:
    datasource1: #sqlserver
        url: jdbc:sqlserver://localhost:1433;DatabaseName=weixin
        username: sa
        password: 123456
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/weixin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用c3p0数据源
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    messages:
    #配置国际化
      basename: i18n.login
    thymeleaf:
      cache: false
    mvc:
      date-format: yyyy-MM-dd
#    mvc:
#      view:
#        # 定位static下的目录
#        prefix: /
#        # 给返回的页面添加后缀名 .html
#        suffix: .html
#      #设定静态文件路径 /css/1.css
#      static-path-pattern: /**

mybatis:
   mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
   type-aliases-package: com.joey.springboot.model  # 注意：对应实体类的路径

wechat:
  AppId: 1
  AppCode: 2

---

server:
  port:9090

---
